# is null 연산자
특정 컬럼 혹은 값이 null 값 인지 아닌지를 판단하는 연산자 이다. is null 혹은 is not null 유무를 판단한다. 

# is null 기본 문법 - column_name 컬럼의 값이 null인 집합을 출력.
# select 
#     *
# from 
#   tabel_name
# where 
#   column_name 
#   is null; 

# in not null 기본 문법 - column_name 컬럼의 값이 null이 아 집합을 출력.
# select 
#     *
# from 
#   tabel_name
# where 
#   column_name 
#   is not null; 
------------------------------------------------
# 실습 준비 
# 1. contacts 라는 태이블 생성
create table contacts 
(
  id int generated by default as identity 
, first_name varchar(50) not null 
, last_name varchar(50) not null 
, email varchar(255) not null
, phone varchar(15) 
, primary key (id)
);

# 2. contacts 태이블 안에 데이터 생성 
insert 
 into
 contacts(first_name, last_name, email, phone)
values
 ('John', 'Doe', 'john.doe@example.com', null),
 ('Lily', 'Bush', 'lily.bush@example.com', '(408-234-2764)');

# 3. 커
commit;
 
# 4. 데이터 확인 
select 
   *
from 
   contacts;
   
-------------------------------------------------

# 실습 예제 1 - phone 컬럼의 값이 null인 집합을 출력하고자 한다.
select
	id,
	first_name,
	last_name,
	email,
	phone
from
	contacts
where
	phone = null ;
-- null 값이 존재하지만 결과가 나오지 않았다. 이말은 결과 집합이 공집합 이므로 null은 '='연산으로 비교할 수 없다.

# 실습 예제 2 - 그래서 phone 컬럼의 값이 null인 집합을 출력하고자 하면 is 를 사용한다.
select
	id,
	first_name,
	last_name,
	email,
	phone
from
	contacts
where
	phone is null ;
	
# 실습 예제 3 - phone 컬럼의 값이 null이 아닌 집합을 출력하고자 한.
select
	id,
	first_name,
	last_name,
	email,
	phone
from
	contacts
where
	phone is not null ;
